
# Overall filter parameters
min_particles:        100       # 100,500
max_particles:        10000     # 5000
update_min_d:         0.1       # 0.2
update_min_a:         0.26    # 0.5235
initial_pose_x:       0.0       # 0.0
initial_pose_y:       0.0       # 0.0

# Odometery model parameters
odom_model_type:  diff-corrected
odom_frame_id:    odom
base_frame_id:    robot_footprint
global_frame_id:  map
